name: Testes de API - Trabalho Final

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Subir a API em background
        run: npm start &
        env:
          PORT: 3000
          MONGODB_URI: mongodb://127.0.0.1:27017/gestao-de-alunos

      - name: Aguardar inicialização do servidor
        run: sleep 3

      - name: Executar testes e gerar relatório
        run: npm test
        env:
          BASE_URL: ${{ secrets.URL_BASE}}
          MONGODB_URI: mongodb://127.0.0.1:27017/gestao-de-alunos
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

      - name: Salvar Relatório de Testes como Artefato
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: relatorio-testes-mochawesome
          path: mochawesome-report/
